x-api-base: &api-base
  image: sua-org/sua-api:latest
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    - PORT=8080
  restart: unless-stopped
  deploy:
    resources:
      limits:
        cpus: "0.10"
        memory: 25M
  networks:
    - rinha-net

services:
  api1:
    <<: *api-base

  api2:
    <<: *api-base

  api3:
    <<: *api-base

  api4:
    <<: *api-base

  api5:
    <<: *api-base

  api6:
    <<: *api-base

  lb:
    image: sua-org/seu-lb:latest
    build:
      context: ./lb
      dockerfile: Dockerfile
    environment:
      - BACKENDS=http://api1:8080,http://api2:8080,http://api3:8080,http://api4:8080,http://api5:8080,http://api6:8080
      - LB_LOG=false
    ports:
      - "9999:8080"
    restart: unless-stopped
    depends_on:
      - api1
      - api2
      - api3
      - api4
      - api5
      - api6
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: 100M
    networks:
      - rinha-net

networks:
  rinha-net:
    driver: bridge
